version: "3.7"

services:
  mongodb:
    image: mongo:latest
    container_name: surgedb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: chandur
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: surge
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro


  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    depends_on: 
      - mongodb
    ports:
      - 8090:8090


  frontend:
    container_name: frontend
    stdin_open: true
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    depends_on: 
      - backend
    ports:
      - 8081:8081
